# Generated by Django 2.0.6 on 2018-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o2', models.FloatField()),
                ('co', models.FloatField()),
                ('ch4', models.FloatField()),
                ('co2', models.FloatField()),
                ('h2', models.FloatField()),
                ('n2', models.FloatField()),
            ],
        ),
    ]
