# Generated by Django 2.0.6 on 2018-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasdb',
            name='c2h4',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
