# Generated by Django 2.0.6 on 2018-06-20 09:33

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('datacoll', '0002_gasdb_c2h4'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasdb',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
    ]
